optimizer:
  name: "RMSProp"
  learning_rate: 0.001
  weight_decay: 0
  epsilon: 0.00000001
  alpha: 0.99
  momentum: 0

data:
  batch_size: 64
  oversampling: False
  class_weights: False

model:
  name: Cifar10LowGPUCNN

trainer:
  epochs: 5

experiment:
  project_name: "Cifar10"
  checkpoint_path: "checkpoints/cifar10"
  metric_monitor: "val/accuracy"
  metric_mode: "max"
