optimizer:
  name: "RMSProp"
  learning_rate: 0.000005
  weight_decay: 0
  epsilon: 0.00000001
  alpha: 0.99
  momentum: 0

data:
  batch_size: 16
  oversampling: False
  class_weights: False

model:
  name: EmbryosLowGPUCNN

trainer:
  epochs: 100

experiment:
  project_name: "Embryos"
  checkpoint_path: "checkpoints/embryos/lowgpucnn/default"
  metric_monitor: "val/auroc"
  metric_mode: "max"
